#!/usr/bin/env bash
# Get the hostname of the server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# creating an index file
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

#creating custom 404
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# creating a redirect
redi_value=\
"location /redirect_me {
      return 301 https://sites.google.com/view/mederhoo-portfolio/home;
      }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }"
if ! grep -q $redi_value /etc/nginx/sites-enabled/default; then
    sudo sed -i "/server_name _;/a $redi_value" /etc/nginx/sites-enabled/default

hostname=$(hostname)

# Check if the add_header directive already exists in the Nginx configuration
if ! grep -q "add_header X-Served-By $hostname;" /etc/nginx/sites-enabled/default; then
    # Add the add_header directive to the Nginx configuration
    sudo sed -i "/server_name _;/a add_header X-Served-By $hostname;" /etc/nginx/sites-enabled/default

    # Reload Nginx to apply changes
    sudo service nginx reload
else
    echo "add_header directive already exists in Nginx configuration."
fi
