#!/usr/bin/env bash
# Get the hostname of the server
sudo sed -i "/server_name _;/a add_header X-Served-By $hostname;" /etc/nginx/sites-enabled/default
# Reload Nginx to apply changes
sudo service nginx restart
