#!/usr/bin/env bash

# Script to connect to a server using a private key

# Define the server's IP address or hostname
my_server_address="3.80.19.171"

# Define the private key file path
private_key_path="~/.ssh/school"

# Connect to the server using ssh
ssh -i "$private_key_path" ubuntu@$my_server_address
